<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-NJAAO8L" failures="1" tests="7" name="test.CreateAccountTest" time="25.807" errors="0" timestamp="2020-05-24T18:26:54 EET" skipped="0">
  <testcase classname="test.CreateAccountTest" name="verifyRegisteration_isSuccessful" time="6.876">
    <failure message="expected [Welcome to your account. Here you can manage all of your personal information and orders] but found [Welcome to your account. Here you can manage all of your personal information and orders.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Welcome to your account. Here you can manage all of your personal information and orders] but found [Welcome to your account. Here you can manage all of your personal information and orders.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at test.CreateAccountTest.verifyRegisteration_isSuccessful(CreateAccountTest.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyRegisteration_isSuccessful -->
  <system-out/>
  <testcase classname="test.CreateAccountTest" name="verifyRegisteration_usingInvalidEmailFormat_fails" time="3.154"/>
  <system-out/>
  <testcase classname="test.CreateAccountTest" name="verifyRegisteration_usingInvalidEmailFormat_fails" time="3.112"/>
  <system-out/>
  <testcase classname="test.CreateAccountTest" name="verifyRegisteration_usingInvalidEmailFormat_fails" time="2.187"/>
  <system-out/>
  <testcase classname="test.CreateAccountTest" name="verifyRegisteration_usingInvalidEmailFormat_fails" time="2.078"/>
  <system-out/>
  <testcase classname="test.CreateAccountTest" name="verifyRegisteration_usingInvalidEmailFormat_fails" time="3.740"/>
  <system-out/>
  <testcase classname="test.CreateAccountTest" name="verifyRegisteration_usingValidEmail_naviagtesToRegisterationPage" time="4.660"/>
  <system-out/>
</testsuite> <!-- test.CreateAccountTest -->
